# 🛠️ Data Cleaning, Preprocessing & Feature Engineering

In [1]:
# Step 1: Import required Python libraries for data manipulation
import pandas as pd
import numpy as np

In [7]:
# Step 2: Load raw supply chain dataset into pandas DataFrame
df= pd.read_csv(r"C:\Users\ASUS\Desktop\Supply Chain Analytics\supply_chain_dataset1.csv")

In [ ]:
# Step 3: Check data dimensions (rows, columns) and inspect first rows

In [11]:
df.shape

(91250, 15)

In [10]:
df.head()

,Date,SKU_ID,Warehouse_ID,Supplier_ID,Region,Units_Sold,Inventory_Level,Supplier_Lead_Time_Days,Reorder_Point,Order_Quantity,Unit_Cost,Unit_Price,Promotion_Flag,Stockout_Flag,Demand_Forecast
0,2024-01-01,SKU_1,WH_1,SUP_8,West,10,592,14,379,0,13.95,20.48,0,0,8.52
1,2024-01-02,SKU_1,WH_1,SUP_8,West,17,575,14,379,0,13.95,20.48,0,0,18.63
2,2024-01-03,SKU_1,WH_1,SUP_8,North,35,540,14,379,0,13.95,20.48,1,0,39.62
3,2024-01-04,SKU_1,WH_1,SUP_8,South,24,516,14,379,0,13.95,20.48,0,0,19.43
4,2024-01-05,SKU_1,WH_1,SUP_8,West,21,495,14,379,0,13.95,20.48,0,0,18.70

In [2]:
# Step 4: Perform data quality audit (duplicates & missing values)

In [12]:
df.duplicated().sum()

np.int64(0)

In [13]:
df.isnull().sum()

Date                       0
SKU_ID                     0
Warehouse_ID               0
Supplier_ID                0
Region                     0
Units_Sold                 0
Inventory_Level            0
Supplier_Lead_Time_Days    0
Reorder_Point              0
Order_Quantity             0
Unit_Cost                  0
Unit_Price                 0
Promotion_Flag             0
Stockout_Flag              0
Demand_Forecast            0
dtype: int64

In [15]:
# Step 5: Standardize column names to lowercase for database compatibility
df.columns = df.columns.str.lower()

In [16]:
df.columns

Index(['date', 'sku_id', 'warehouse_id', 'supplier_id', 'region', 'units_sold',
       'inventory_level', 'supplier_lead_time_days', 'reorder_point',
       'order_quantity', 'unit_cost', 'unit_price', 'promotion_flag',
       'stockout_flag', 'demand_forecast'],
      dtype='str')

In [17]:
df.head()

,date,sku_id,warehouse_id,supplier_id,region,units_sold,inventory_level,supplier_lead_time_days,reorder_point,order_quantity,unit_cost,unit_price,promotion_flag,stockout_flag,demand_forecast
0,2024-01-01,SKU_1,WH_1,SUP_8,West,10,592,14,379,0,13.95,20.48,0,0,8.52
1,2024-01-02,SKU_1,WH_1,SUP_8,West,17,575,14,379,0,13.95,20.48,0,0,18.63
2,2024-01-03,SKU_1,WH_1,SUP_8,North,35,540,14,379,0,13.95,20.48,1,0,39.62
3,2024-01-04,SKU_1,WH_1,SUP_8,South,24,516,14,379,0,13.95,20.48,0,0,19.43
4,2024-01-05,SKU_1,WH_1,SUP_8,West,21,495,14,379,0,13.95,20.48,0,0,18.70

In [18]:
df['supplier_id'].unique()

<ArrowStringArray>
[ 'SUP_8',  'SUP_5',  'SUP_9',  'SUP_2',  'SUP_7', 'SUP_10',  'SUP_6',
  'SUP_4',  'SUP_3',  'SUP_1']
Length: 10, dtype: str

In [25]:
df['sku_id'].unique()

<ArrowStringArray>
[ 'SKU_1',  'SKU_2',  'SKU_3',  'SKU_4',  'SKU_5',  'SKU_6',  'SKU_7',
  'SKU_8',  'SKU_9', 'SKU_10', 'SKU_11', 'SKU_12', 'SKU_13', 'SKU_14',
 'SKU_15', 'SKU_16', 'SKU_17', 'SKU_18', 'SKU_19', 'SKU_20', 'SKU_21',
 'SKU_22', 'SKU_23', 'SKU_24', 'SKU_25', 'SKU_26', 'SKU_27', 'SKU_28',
 'SKU_29', 'SKU_30', 'SKU_31', 'SKU_32', 'SKU_33', 'SKU_34', 'SKU_35',
 'SKU_36', 'SKU_37', 'SKU_38', 'SKU_39', 'SKU_40', 'SKU_41', 'SKU_42',
 'SKU_43', 'SKU_44', 'SKU_45', 'SKU_46', 'SKU_47', 'SKU_48', 'SKU_49',
 'SKU_50']
Length: 50, dtype: str

In [19]:
df.dtypes

date                           str
sku_id                         str
warehouse_id                   str
supplier_id                    str
region                         str
units_sold                   int64
inventory_level              int64
supplier_lead_time_days      int64
reorder_point                int64
order_quantity               int64
unit_cost                  float64
unit_price                 float64
promotion_flag               int64
stockout_flag                int64
demand_forecast            float64
dtype: object

In [20]:
# Step 6: Cast 'date' column to datetime data type
df['date'] = pd.to_datetime(df['date'])

In [21]:
# Step 7: Feature Engineering - Financial Metrics (Revenue, Cost, Profit, Margin)
df['total_revenue'] = df['units_sold'] * df['unit_price']
df['total_cost'] = df['units_sold'] * df['unit_cost']
df['profit'] = df['total_revenue'] - df['total_cost']
df['profit_margin'] = (df['profit'] / df['total_revenue']).fillna(0)

In [22]:
# Step 8: Feature Engineering - Reorder Risk & Lost Revenue Calculations
df['below_reorder_flag'] = (df['inventory_level'] <= df['reorder_point']).astype(int)
df['lost_sales_units'] = np.where(df['stockout_flag'] == 1, np.maximum(0, df['demand_forecast'] - df['units_sold']), 0)
df['lost_revenue'] = df['lost_sales_units'] * df['unit_price']

In [23]:
# Step 9: Feature Engineering - Demand Forecast Error & Absolute Error
df['forecast_error'] = df['units_sold'] - df['demand_forecast']
df['abs_forecast_error'] = np.abs(df['forecast_error'])

In [24]:
df.head(10)

,date,sku_id,warehouse_id,supplier_id,region,units_sold,inventory_level,supplier_lead_time_days,reorder_point,order_quantity,...,demand_forecast,total_revenue,total_cost,profit,profit_margin,below_reorder_flag,lost_sales_units,lost_revenue,forecast_error,abs_forecast_error
0,2024-01-01,SKU_1,WH_1,SUP_8,West,10,592,14,379,0,...,8.52,204.80,139.50,65.30,0.318848,0,0.0,0.0,1.48,1.48
1,2024-01-02,SKU_1,WH_1,SUP_8,West,17,575,14,379,0,...,18.63,348.16,237.15,111.01,0.318848,0,0.0,0.0,-1.63,1.63
2,2024-01-03,SKU_1,WH_1,SUP_8,North,35,540,14,379,0,...,39.62,716.80,488.25,228.55,0.318848,0,0.0,0.0,-4.62,4.62
3,2024-01-04,SKU_1,WH_1,SUP_8,South,24,516,14,379,0,...,19.43,491.52,334.80,156.72,0.318848,0,0.0,0.0,4.57,4.57
4,2024-01-05,SKU_1,WH_1,SUP_8,West,21,495,14,379,0,...,18.70,430.08,292.95,137.13,0.318848,0,0.0,0.0,2.30,2.30
5,2024-01-06,SKU_1,WH_1,SUP_8,East,18,477,14,379,0,...,18.33,368.64,251.10,117.54,0.318848,0,0.0,0.0,-0.33,0.33
6,2024-01-07,SKU_1,WH_1,SUP_8,North,19,458,14,379,0,...,18.91,389.12,265.05,124.07,0.318848,0,0.0,0.0,0.09,0.09
7,2024-01-08,SKU_1,WH_1,SUP_8,North,23,435,14,379,0,...,25.84,471.04,320.85,150.19,0.318848,0,0.0,0.0,-2.84,2.84
8,2024-01-09,SKU_1,WH_1,SUP_8,West,25,410,14,379,0,...,21.70,512.00,348.75,163.25,0.318848,0,0.0,0.0,3.30,3.30
9,2024-01-10,SKU_1,WH_1,SUP_8,South,25,385,14,379,0,...,21.34,512.00,348.75,163.25,0.318848,0,0.0,0.0,3.66,3.66

In [26]:
# Step 10: Export processed 24-column dataset to CSV
df.to_csv("cleaned_supply_chain_dataset1" , index=False)

In [3]:
df = pd.read_csv(r"C:\Users\ASUS\Desktop\Supply Chain Analytics\cleaned_supply_chain_dataset1.csv")
df.head()

,date,sku_id,warehouse_id,supplier_id,region,units_sold,inventory_level,supplier_lead_time_days,reorder_point,order_quantity,...,demand_forecast,total_revenue,total_cost,profit,profit_margin,below_reorder_flag,lost_sales_units,lost_revenue,forecast_error,abs_forecast_error
0,2024-01-01,SKU_1,WH_1,SUP_8,West,10,592,14,379,0,...,8.52,204.80,139.50,65.30,0.318848,0,0.0,0.0,1.48,1.48
1,2024-01-02,SKU_1,WH_1,SUP_8,West,17,575,14,379,0,...,18.63,348.16,237.15,111.01,0.318848,0,0.0,0.0,-1.63,1.63
2,2024-01-03,SKU_1,WH_1,SUP_8,North,35,540,14,379,0,...,39.62,716.80,488.25,228.55,0.318848,0,0.0,0.0,-4.62,4.62
3,2024-01-04,SKU_1,WH_1,SUP_8,South,24,516,14,379,0,...,19.43,491.52,334.80,156.72,0.318848,0,0.0,0.0,4.57,4.57
4,2024-01-05,SKU_1,WH_1,SUP_8,West,21,495,14,379,0,...,18.70,430.08,292.95,137.13,0.318848,0,0.0,0.0,2.30,2.30

In [ ]:
df['region'].